### ISSUE TITLE
Написать open-api спецификацию для exam-conduct-service

### ISSUE THREAD

**Issue by vitekkor** [se-brown-2023/automated-testing-applicants-service#37]
* Написать open-api спецификацию для exam-conduct-service в формате yml
* Положить в ресурсы модуля
* Настроить авто генерацию контроллеров:
```kotlin
plugins {
    // ...
    id("org.openapi.generator")  version "7.1.0"
    // ...
}

// ...

openApiGenerate {
    generatorName.set("spring")
    validateSpec.set(true)
    inputSpec.set("$projectDir/src/main/resources/user-service-api.yaml") // path to spec
    outputDir.set("${layout.buildDirectory.asFile.get()}/generated/java")
    apiPackage.set("com.sebrown2023.controller")
    modelPackage.set("com.sebrown2023.model.dto")
    generateApiTests.set(false)
    generateModelTests.set(false)
    generateModelDocumentation.set(false)

    globalProperties.set(
        mapOf(
            "generateSupportingFiles" to "false",
            "models" to "",
            "apis" to "",
        ),
    )


    configOptions.set(
        mapOf(
            "documentationProvider" to "none",
            "generatedConstructorWithRequiredArgs" to "true",
            "openApiNullable" to "false",
            "useSpringBoot3" to "true",
            "java8" to "false",
            "skipDefaultInterface" to "true",
            "interfaceOnly" to "true",
            "serviceInterface" to "true",
            "useTags" to "true",
            "fullJavaUtil" to "false",
            "hideGenerationTimestamp" to "true",
            "sourceFolder" to "",
            "library" to "spring-boot",
            "serializationLibrary" to "jackson",
        ),
    )
}
```

**Comment by axothy** [comment]
А чтобы непосредственно сгенерировать интерфейсы, чтобы они появились в com.sebrown2023.controller  - что сделать надо? просто gradle build ?

`openApiGenerate {
    generatorName.set("spring")
    validateSpec.set(true)
    inputSpec.set("$projectDir/src/main/resources/exam-conduct-service-api.yml") // path to spec
    outputDir.set("${layout.buildDirectory.asFile.get()}/generated/openapi")
    apiPackage.set("com.sebrown2023.controller")
    modelPackage.set("com.sebrown2023.model.dto")
    generateApiTests.set(false)
    generateModelTests.set(false)
    generateModelDocumentation.set(false)

    globalProperties.set(
        mapOf(
            "generateSupportingFiles" to "false",
            "models" to "",
            "apis" to "",
        ),
    )


    configOptions.set(
        mapOf(
            "documentationProvider" to "none",
            "generatedConstructorWithRequiredArgs" to "true",
            "openApiNullable" to "false",
            "useSpringBoot3" to "true",
            "java8" to "false",
            "skipDefaultInterface" to "true",
            "interfaceOnly" to "true",
            "serviceInterface" to "true",
            "useTags" to "true",
            "fullJavaUtil" to "false",
            "hideGenerationTimestamp" to "true",
            "sourceFolder" to "",
            "library" to "spring-boot",
            "serializationLibrary" to "jackson",
        ),
    )
}`

**Comment by vitekkor** [comment]
@axothy 
Добавить ещё _обязательно_ в build.gradle.kts:
```
tasks.withType<JavaCompile> {
    dependsOn("openApiGenerate")
}
```

А потом можно и `gradle build`
Или `gradle :exam-conduct-service:openApiGenerate`

**Comment by vitekkor** [comment]
@axothy Ещё я забыл про это:
```kotlin
sourceSets.main {
    java.srcDirs("${layout.buildDirectory.asFile.get()}/generated/java")
}
```
